repos:
  # 1. Les outils de base (nettoyage automatique)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace   # Supprime les espaces inutiles en fin de ligne (Ton erreur C0303 !)
      - id: end-of-file-fixer     # S'assure qu'il y a une ligne vide à la fin du fichier
      - id: check-yaml            # Vérifie que ce fichier config est valide

  # 2. Pylint (Analyse statique)
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: poetry run pylint
        language: system
        types: [python]
        args: ["code.py"]         # On cible UNIQUEMENT ton fichier principal
